### PR TITLE
Fix metagenomics input and provide more resources

### PR DESCRIPTION
**Pull request by haydenm**
The metagenomics tools took as input the file "{sample}.bam" in the
source subdir, but this file is not created when demultiplexing raw
data and the snakemake pipeline is not setup to create this file.
Thus, snakemake is unable to find input for the metagenomics tools.
This fix changes the input to be "{sample}.raw.bam" in the per_sample
subdir. The snakemake pipeline is able to create this file even
when demultiplexing raw reads, so it is able to create input for
the metagenomics tasks.

This also gives the metagenomics tools more resources; it requests
more memory and a queue with longer runtime.

### CODE REVIEW

**Comment by dpark01** [comment]
Thanks @haydenm ! It makes sense you'd have to update the test case to match your changes, just ask @yesimon if you need assistance.

**Comment by tomkinsc** [comment]
Could use some help here, @yesimon.

**Comment by dpark01** [comment]
Hm, looks like it's still not putting the test bam in the 01_per_sample directory for the snakemake test. I can take a look after the weekend (I don't think it's so urgent that we have to get this sorted before then).

**Comment by dpark01** [comment]
perfect!

**Pull request merged**
