### PR TITLE
Set shell executable to /bin/bash on snakemake rules

### PR DESCRIPTION
**Pull request by yesimon**

### CODE REVIEW

**Comment by tomkinsc** [comment]
This seems fine, but were there issues previously?

**Comment by dpark01** [comment]
If you set this in common.rules and reports_only, why is it needed elsewhere?

**Comment by yesimon** [comment]
@tomkinsc If you don't specify it just uses the user's shell, but I think we want to standardize on bash.

@dpark01 let me try that

**Comment by yesimon** [comment]
Why did the first build fail? 😕

**Comment by tomkinsc** [comment]
It was a transient Travis error (couldn't access GitHub).

**Pull request merged**
