### PR TITLE
SampleSheet reader now uses csv.reader() rather than str.split()

### PR DESCRIPTION
**Pull request by tomkinsc**
Previously, commas in sample names could cause problems when reading in sample sheets, since the reader was naively splitting on commas. This incorporates changes to uses Python’s csv.reader() to parse SampleSheet.csv rows, with a custom dialect to support escaping quotes with backslash characters. It also adds a unit test with a SampleSheet that was problematic prior to these changes.

### CODE REVIEW

**Comment by dpark01** [comment]
Thanks!

**Comment by dpark01** [comment]
Merge in some of my branch, I got started a bit

--
Daniel J. Park, PhD
Group Leader, Viral Computational Genomics
Broad Institute of MIT and Harvard
Tel: +1-617-714-8526
dpark@broadinstitute.org
http://www.broadinstitute.org/bios/daniel-park

**Comment by tomkinsc** [comment]
Ok, I merged in what you had in `dp-samplesheet`, and removed some duplication since I'm already stripping whitespace from all elements in a row.

**Comment by tomkinsc** [comment]
This should be OK to merge.

**Pull request merged**
