### PR TITLE
Use conda python for python packages on travis.

### PR DESCRIPTION
**Pull request by yesimon**
Python packages installed to the 'default' environment.

### CODE REVIEW

**Comment by yesimon** [comment]
I'm not sure why coveralls is upset

**Comment by yesimon** [comment]
I'm setting the appropriate Python version in 'conda create'

**Comment by yesimon** [comment]
Another note here is that Travis's python versions are basically bypassed and we're installing our own versions of python. I think this is relatively reasonable since a move to conda would suggest that installing conda's python works well and is necessary.

**Comment by dpark01** [comment]
@yesimon yeah been pondering that move anyway, I just didn't realize conda came with multiple versions of py3

**Comment by yesimon** [comment]
@dpark01 So I double checked and it looks like the 3.4 tests on travis are picking up python3.5 from the miniconda cache. We'll need to have a cache per python version?

**Comment by dpark01** [comment]
Wait--the only persistent cache is handled by Travis, and that's definitely separate for each point on the build matrix (which in our case, is just the three Python versions). Not sure how that got mixed up but I assume you've tried clearing the Travis cache and rebuilding?

**Comment by yesimon** [comment]
Sorry had to correct a typo 😦

**Comment by yesimon** [comment]
@tomkinsc don't forget to update the bioconda recipes, the biopython and matplotlib versions were also updated

**Comment by tomkinsc** [comment]
Thanks. Already in the staged commit! I'm the one who added biopython 1.68 to bioconda. :)

**Pull request merged**
