### PR TITLE
Revamp of metagenomics rules

### PR DESCRIPTION
**Pull request by yesimon**
Add support for krakenuniq, kaiju to replace kraken and diamond in default pipelines.

Both rely on customized krakenuniq/kaiju packages for custom functionality, like loading database
from pipe or printing out all taxa hits (kaiju).

Krona fixed to use hit counts as scores in report files directly, instead of counting the
individual read classifications (which takes a long time).

Includes changes from #915 and also some pytest deprecation fixes: `s/log.warn(/log.warning(/`, `runslow` command line configuration.

### CODE REVIEW

**Comment by dpark01** [comment]
Fixes #777.

**Comment by dpark01** [comment]
Do we know how this fares with single-end read BAM input? #820

**Comment by yesimon** [comment]
The fork of krakenuniq is the `sy-multiple` branch: https://github.com/yesimon/krakenuniq/tree/sy-multiple.

The fork of kaiju is minor and is in the `sy-report-viruses` branch: https://github.com/yesimon/kaiju/tree/sy-report-viruses

**Comment by yesimon** [comment]
Incorporated in #944

**Pull request closed without merging**
