### PR TITLE
Re-pipify diamond

### PR DESCRIPTION
**Pull request by yesimon**
Joining stdout and stdin pipes doesn't seem to deadlock anymore.

Also reduce krona output to not save query names or spurious scores.

### CODE REVIEW

**Comment by yesimon** [comment]
It's weird that a mock in a unit test is throwing an exception and it still passes...

**Comment by dpark01** [comment]
Where is this exception (do you have a Travis link)?

**Comment by yesimon** [comment]
https://travis-ci.org/broadinstitute/viral-ngs/jobs/315577091 

I fixed the exception - it was just a mocking issue.

**Comment by yesimon** [comment]
This looks fine now

**Pull request closed without merging**
